### ISSUE TITLE
Problem on installation

### ISSUE THREAD

**Issue by MiloDeroussi** [HoangGiang93/URoboViz#10]
Hello, I'm trying to install your plugin for a project. But I'm having a lot of trouble installing it and I haven't found any solutions, so I'm asking for your help.

I followed the tutorial in the wiki for Unreal version 4.27.2. Everything passes compilation, but when I try to relaunch with CTRL+SHIFT+D I get the following errors:

![Capture d’écran du 2024-09-18 06-56-30](https://github.com/user-attachments/assets/e587651c-b3f1-46a8-835e-0b8fc0f3de28)

![Capture d’écran du 2024-09-18 06-59-40](https://github.com/user-attachments/assets/6dff194a-6de7-4e54-8cd0-817d79e8b5e5)

In the terminal, I also have these warnings when the crash occurs:

![Capture d’écran du 2024-09-18 08-35-24](https://github.com/user-attachments/assets/ee5d292a-93ea-48f8-adc1-36c41437fec7)

Do you have any idea how I could fix these ?

**Comment by HoangGiang93** [comment]
I haven't encountered this error before. It looks like the UASSET files weren't cloned properly. Did you install git lfs?

**Comment by MiloDeroussi** [comment]
Thank you it was indeed one of the problem.
If anyone as similar warning, you should to link your libpgm to specificaly 5.2 version : sudo ln -s /path/to/libpgm-5.3.so.0 /usr/lib/libpgm-5.2.so.0
