### ISSUE TITLE
Control the robot from code

### ISSUE THREAD

**Issue by Nash-dc** [HoangGiang93/URoboViz#4]
Hello Mr.Hoang,
It's me again. Thanks for your help when I was building this project.
I would like to control the robot from the code. So I added the ROS subscriber `/joint_states` then started the simulation and typed:
`rostopic pub /joint_states sensor_msgs/JointState '{header: {stamp: now, frame_id: base_link}, name: [panda_2_joint6],position:[200],velocity:[20],effort:[5]}
`
this joint didn't move however. I was wondering if it is possible that I can control this DualPanda from Terminal.If not, can I control this Robot by implementing the correct Actor Class to the **_RoboManager_**?
Thank you in advance!

**Comment by HoangGiang93** [comment]
Hi, in the ROS subscriber in RoboManager did you specify the correct name of the JointController?
