### ISSUE TITLE
Integrate with MoveIt!

### ISSUE THREAD

**Issue by aiolosgs** [HoangGiang93/URoboViz#7]
Hello Mr.Hoang,
Thanks for your great work. I've already done some work with ROS and MoveIt! for robot simulation, and I'm not familiar with MuJoCo, so I wonder if I can integrate your project with my work in MoveIt!. If so, any advice on how to implement it?

**Comment by HoangGiang93** [comment]
URoboViz works just like RViz, you just need to publish the joint_state to the corresponding topic and URoboViz will visualize that for you
