### ISSUE TITLE
Move the objects in MuJoCo

### ISSUE THREAD

**Issue by hoangledoan** [HoangGiang93/URoboViz#9]
Hello Mr. Hoang,

I deeply appreciate this wonderful plugin, which I've already integrated into my project. I've successfully executed your *pick and place demo*, and it appears flawless. However, I'm now intrigued about manipulating the object within the mojoco-sim environment programmatically.

In the context of your *pick and place* demo, I'm eager to understand how I can dynamically update the *position and orientation* of the cube or cylinder through code control.I attempted object control using giskardpy, but soon realized that the object only exists in the MuJoCo demo, not in the ROS world.

 Is there a mechanism analogous to subscribing to a specific topic and receiving pose messages, similar to the functionality in ROS? Your guidance on this matter would be immensely valuable to me.

**Comment by HoangGiang93** [comment]
Yes it is. In URoboViz you can spawn an object using the rosservice `/unreal/spawn_objects`. You can check [this](https://github.com/HoangGiang93/mujoco_robots/blob/main/franka/franka_control/script/test_dual_joint_pick_place_ue_1.py#L73-L125) to see how it's called from a script. From Unreal side, you need to add the SpawnObjectServer in ROSServiceServer in RoboManager. To control the spawned objects, just Tick the AddObjectInMuJoCo. The objects will be controlled by MuJoCo if there exists some control signal in ROS topic `/mujoco/object_states`. Don't forget to launch the `rosbridge_server` before Run the Demo in Unreal

**Comment by HoangGiang93** [comment]
And if you don't like ROS communication, I'm also developing an interface to communicate between different physics engine in [Multiverse](https://github.com/Multiverse-Framework/Multiverse) using TCP

**Comment by hoangledoan** [comment]
Thank you for your response. I understand that my initial description might not have been precise enough.
My project revolves around force rendering, and my goal is to precisely move objects within the MuJoCo simulation by providing them with accurate poses.
After reviewing the [mj_ros.cpp](https://github.com/HoangGiang93/mujoco_sim/blob/main/src/mujoco_sim/mj_ros.cpp) file, I noticed that there's no available service for updating object poses in MuJoCo. Even when using [mujoco-py](https://github.com/openai/mujoco-py) to manipulate objects, I faced challenges that resulted in unsuccessful attempts to achieve the desired result.

I attempted to create my own "move object in Mujoco" service, but unfortunately, my efforts have not yielded successful results.

By the way, I find The Multiverse to be excellent and easily comprehensible. I'm currently utilizing it for force rendering tasks; however, I'm facing a similar challenge in this regard.

**Comment by HoangGiang93** [comment]
In MuJoCo you can't directly set the xpos or xquat of a body, those variables are read-only.
To set a position of a body in MuJoCo either you need to calculate the corresponding joint position qpos and set it, or use the mocap_body instead. mocap_body let you set the postion and quaternion easily, but it doesn't have velocity.

**Comment by hoangledoan** [comment]
Could you please give a simple example on utilizing 'mocap-body' to move objects,like the cube in the demo?I am unsure the steps to take.I would appreciate for your help.

**Comment by HoangGiang93** [comment]
Have a look at [this](https://github.com/Multiverse-Framework/Multiverse-MuJoCo-Connector/blob/main/mujoco_sim/src/mujoco_sim/mj_multiverse_client.cpp#L545-L547) snippets of code, I bind the values of these d->mocap_pos so I can later control them like [this](https://github.com/Multiverse-Framework/Multiverse-MuJoCo-Connector/blob/main/mujoco_sim/src/mujoco_sim/mj_multiverse_client.cpp#L710).
